name: JavaScript Checks

on:
  pull_request:
    branches:
      - main # Adjust the branch name as needed

jobs:
  lint-and-test:
    name: Linting and Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Pull Request
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install Dependencies
        run: npm install # Assuming you're using npm for managing dependencies

      - name: Run Linter
        run: npm run lint # Adjust the command to run your linter

      - name: Run Tests
        run: npm test # Adjust the command to run your tests


      # You can add more steps as needed, such as building assets, deploying, etc.
